KSP-RO/ROKerbalism

- GameData/Kerbalism/Support/Kopernicus.cfg
- GameData/Kerbalism/Support/NearFuture.cfg
- GameData/Kerbalism/Support/SSTU.cfg
- GameData/KerbalismConfig/System/Misc.cfg
- GameData/KerbalismConfig/System/Reliability.cfg
see
https://github.com/Standecco/ROKerbalism/issues/13
This is kind of a reminder, but could ofc be taken into account as is.
> WarpFixer becomes SolarPanelFixer

- GameData/KerbalismConfig/System/Science/Configure.cfg
- GameData/KerbalismConfig/System/Science/CrewScience/Experiments/MatureCapsuleExperiments.cfg
- GameData/KerbalismConfig/System/Science/CrewScience/Experiments/SecondGenExperiments.cfg
add crew science to Advanced Command Pod and from RO and Apollo CM from ROCapsules
> Roc experiments

- GameData/KerbalismConfig/Support/Apollo.cfg
- GameData/KerbalismConfig/System/Habitat.cfg
- GameData/KerbalismConfig/System/Parts.cfg
- GameData/KerbalismConfig/System/Science/Configure.cfg
- GameData/KerbalismConfig/System/Science/CrewScience/Experiments/MatureCapsuleExperiments.cfg
- GameData/KerbalismConfig/System/Science/CrewScience/Experiments/SecondGenExperiments.cfg
adding crew science and life support to several stock/making history pods
> add some missing capsules configs

- GameData/KerbalismConfig/System/Parts.cfg
My 1.6 install only had the inline cockpit for whatever reason.
So didn't realize there was another part needing the same fix
> Scrubber for the other x15-class cockpit

- GameData/KerbalismConfig/Support/ROCapsules.cfg
- GameData/KerbalismConfig/System/Habitat.cfg
- GameData/KerbalismConfig/System/Parts.cfg
Add Kerbalism configs to ETS Apollo parts.
> ROCapsules ETS Apollo configs

- GameData/KerbalismConfig/System/Science/Configure.cfg
-Add ROTanks Probe Core to the list of parts that receive configruable science experiments
-add the 4th tier of the mass spec experiment to probe cores
> ROTProbe core + massspec4

- GameData/KerbalismConfig/Support/US2.cfg
IDK if there's a better way to DRY this up, but this just pastes in the latest from https://github.com/Standecco/ROKerbalism/commit/aebe52a5c1eea2a90916fd6526ca97b9ea0fce31
> Update US2 LSM to match Kerbalism LSM

- GameData/KerbalismConfig/Support/ROCapsules.cfg
- GameData/KerbalismConfig/System/Parts.cfg
Add configs for the new ROC Mercury Parts
> New ROC Mercury

- GameData/KerbalismConfig/Support/ROCapsules.cfg
- GameData/KerbalismConfig/System/Parts.cfg
Add configs for the new ROC Gemini parts
> New Gemini configs

- GameData/KerbalismConfig/System/Parts.cfg
based on similar fix for voskhod
> Make VA TKS pod scrubber strong enough

- GameData/KerbalismConfig/System/Habitat.cfg
make it not quite so much bigger on the inside than the outside
> Better SXT-skylab habitat size

- GameData/KerbalismConfig/System/Habitat.cfg
My eyeballed "3m" was way off for the Mk1. Actually measured things
this time.
> Better habitat dimensions for mk2CrewCabin, Mk1CrewModule

- GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Based on kerbalism-drill, but with 5 times capacity and 4 times mass & cost
> Added kerbalism-large-drill

- GameData/KerbalismConfig/Support/SOCK.cfg
- GameData/KerbalismConfig/System/Habitat.cfg
- GameData/KerbalismConfig/System/Parts.cfg
- GameData/KerbalismConfig/System/Science/CrewScience/Experiments/MatureCapsuleExperiments.cfg
- GameData/KerbalismConfig/System/Science/HardDriveConfigs.cfg
Adds support for SOCK Space Shuttle Orbiter.
**Things I want to do:**
~~Is there a better way to offset the power consumption to be 14 kW?~~
~~Should something be done to the radiator?~~
larger battery? The current battery is the real life size, but the issues with fuel cells turning off makes the time window to fix it very small.
> SOCK configs

- GameData/KerbalismConfig/System/Science/CrewScience/ExperimentValues.cfg
Also rounded the other numbers to be divisible by 3.
> Reduce total time for the high altitude experiments

- GameData/KerbalismConfig/Support/SSS.cfg
- GameData/KerbalismConfig/System/Parts.cfg
SSS configs based on SOCK configs, might be worth merging them into the same file, as they are essentially duplicates.
> Space shuttle system

- GameData/KerbalismConfig/Support/RN_Soyuz.cfg
- GameData/KerbalismConfig/System/Habitat.cfg
- GameData/KerbalismConfig/System/Parts.cfg
Improve RN Soyuz support, and add support for new RN Soyuz parts.
> Improve RN Soyuz Support

- GameData/KerbalismConfig/Support/DECQ_Buran.cfg
- GameData/KerbalismConfig/System/Parts.cfg
> DECQ Buran support

- GameData/KerbalismConfig/Support/ROCapsules.cfg
- GameData/KerbalismConfig/System/Parts.cfg
Add support for ROCapsules BDB Apollo
> Add support for BDB Apollo

- .github/workflows/attachReleaseArtifacts.yml
- GameData/KerbalismConfig/changelog.cfg
Quite stripped down compared to other repos, since no .dll's exist
> Add Common CI

- GameData/KerbalismConfig/System/Habitat.cfg
- GameData/KerbalismConfig/System/Parts.cfg
Add configs for the new RO cockpits and some basic configs for Airplane Plus.
For https://github.com/KSP-RO/RealismOverhaul/pull/2774
> New RO Cockpits, Airplane Plus configs

- GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
- GameData/KerbalismConfig/Support/RealismOverhaul.cfg
- GameData/KerbalismConfig/System/Radiation.cfg
Fix NTR support so all NTRs actually get radiation emitters and generators where needed, and add support for new NTR configs.
For https://github.com/KSP-RO/RealismOverhaul/pull/2771
> Fix NTR support, new configs

- GameData/KerbalismConfig/Support/RealismOverhaul.cfg
Add support for LPNTR config added in https://github.com/KSP-RO/RealismOverhaul/pull/2831
> Add support for LPNTR

- GameData/KerbalismConfig/Settings.cfg
This should make the default storm probability 0% for new saves
> Disable storms by default

- GameData/KerbalismConfig/Localization/de.cfg
- GameData/KerbalismConfig/Localization/en-us.cfg
- GameData/KerbalismConfig/Localization/pt-br.cfg
- GameData/KerbalismConfig/Localization/ru.cfg
- GameData/KerbalismConfig/Localization/zh-cn.cfg
- GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Partial translation from Kerbalism Deafult config.
> Added localization support for some entries, and added (incomplete) Simplified  Chinese localization.

- GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
- GameData/KerbalismConfig/Support/NearFuture.cfg
- GameData/KerbalismConfig/System/Misc.cfg
Add support for RTGs using Polonium-210 (SNAP-3 and Soviet stuff) and Curium-242 (SNAP-11).
> Add support for Polonium and Curium RTGs

- GameData/KerbalismConfig/Support/Fuji.cfg
- GameData/KerbalismConfig/System/Parts.cfg
Originally created by @mikusingularity
> Fuji Kerbalism configs

- GameData/KerbalismConfig/Support/RestockPlus.cfg
for https://github.com/KSP-RO/RealismOverhaul/pull/3024
> Configure ReStockPlus airlock
