GameData/KerbalismConfig/Support/ROCapsules.cfg
added
Support/ROCapsules.cfg
because the RealFuels' ModuleFuelTanks have only been patched for TAC-LS before.
=> Add Support/ROCapsules

GameData/KerbalismConfig/System/Science/HardDriveConfigs.cfg
This is forgotten, stock Kerbalism also does this in favor of MODULE[HardDrive]
=> Remove ModuleScienceContainer

GameData/KerbalismConfig/System/Science/CrewScience/ExperimentValues.cfg, GameData/KerbalismConfig/System/Science/SatelliteScience/ExperimentValues.cfg
Recent commit added a bunch of lines like this:
SampleMass = #$@KERBALISM_CREW_EXPERIMENTS/RP0-FlightControl/SampleMass
But the corresponding objects in ExperimentValues.cfg mostly don't have
a SampleMass field, and this causes a MM error
("cannot parse variable search").
per Got: added a SampleMass=0 field to non-sample experiments.
Alternate fix is to remove SampleMass from the KERBALISM_EXPERIMENT
nodes; not obvious to me which is preferable, so I went with the
option that involved editing fewer files.
=> Fix MM errors for missing variables

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
By volume, fuel cells should consume twice as much H2 as O2, not
the other way around. (H2 + H2 + O2 -> 2 H2O; LH2 and LO2 have roughly
the same volume/mol)
This makes the mass ratios roughly correct (1:8), and is in the same
ballpark as hydrolox engine ratios (considering those usually run
fuel-rich)
Non-kerbalism'ed RO fuel cells use a 1.4:1 ratio instead of 2:1;
no idea where that came from.
=> Fix fuel cell consumption ratios

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
That's where the actual fuel cell parts are. Fuel cells are often
used for life support, but aren't inherently related to life support.
As a side-effect, this means a Gemini capsule still has to research
the fuel cell Power node to be able to use its built-in fuel cells,
putting it on equal footing with a capsule without built-in cells
(like the RO Advanced Capsule)
=> Move fuel cell tech unlocks to Power nodes

GameData/KerbalismConfig/System/Science/Configure.cfg
Workaround for presumed Core bug: if there are fewer available
experiments than slots, the default-selected experiments can't be
deselected. So add a couple of dummy entries.
=> Make probe core experiments removable early-game

GameData/KerbalismConfig/System/Habitat.cfg
Apply the patch :after[RO], because the parts get created in :for[RO]
(I didn't think it mattered for +patches, but without this the patch
never gets applied)
Also use %, in case the 1.25m part gets patched before the +part[]
clones it. (not sure this is needed, was the 1st thing I tried and it
wasn't enough. can't hurt)
=> Fix Prototype Spaceplane habitat size

GameData/KerbalismConfig/System/Comfort.cfg, GameData/KerbalismConfig/System/Parts.cfg
Decrease the base power draw of crewed parts to account for Kerbalism LS increasing draw, and prevent the player from being "charged twice" for life support.
=> Correct capsule power draw to account for LS

GameData/KerbalismConfig/Support/ROCapsules.cfg, GameData/KerbalismConfig/System/Habitat.cfg, GameData/KerbalismConfig/System/Parts.cfg
Add support for ROC-Gemini, and other Geminis. The FASA gemini has had Fuel Cells and a LOX to GOX converter add to its equipment section. The RO Advanced Capsule has also had fuel cells and LOX-GOX converters add because it has its service module built in.
ROC PR: https://github.com/KSP-RO/ROCapsules/pull/16
=> Add support for ROC Gemini

GameData/KerbalismConfig/System/Habitat.cfg, GameData/KerbalismConfig/System/Parts.cfg
- bump up max_pressure to same level as Gemini. This multiplies
time-to-100%-stress by ~10x (!)
- explicitly set a volume, to roughly half the total part volume
(cutting time-to-100%-stress by ~50%)
Main intent is to make Early Space Station parts usable for the
First Space Station rp-1 contract: 30d with at least 2 crew, room for 3.
Without this, a PPD-6 (4 seats) only lasted ~20d with 2 crew.
With this change, that becomes ~100d; probably too much, but a better
starting point. (standecco floated the idea of cutting the pressure bonus in half; 50d wouldn't be bad)
=> Better habitat config for PPD-4/6

GameData/KerbalismConfig/System/Habitat.cfg
Per discord semi-consensus, Mk1-3 Pod is-a Apollo
6 cubic meters is certainly a better approximation than 21!
=> Give Mk1-3 Pod the same volume as Apollo

GameData/KerbalismConfig/System/Science/CrewScience/Experiments/MatureCapsuleExperiments.cfg, GameData/KerbalismConfig/System/Science/CrewScience/Experiments/SecondGenExperiments.cfg
Crew Science was missing for several Soyuz Orbital Modules from the RN Soyuz mod
=> Add RN Soyuz orbital modules to Crew Science

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Found a few new sources for life support parts on the ISS and extrapolated mass numbers from theirs.  All of the masses went up, some significantly. This may put them out of line with estimates for earlier tech counterparts but I haven't found more information on those to cross reference.
https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20170007268.pdf
Found a paper on proposed mars oxygen liquefaction options and updated OX to LOX converter to match those numbers.  Mass dropped and wattage increased, both significantly.
https://www.sciencedirect.com/science/article/pii/S0011227517302187
=> Various life support FIXME's

GameData/KerbalismConfig/System/Habitat.cfg
A bit arbitrary, but better than the defaults it was inheriting
from the 1.25m KerbCan
=> Better habitat stats for RO-Mk1CrewModule

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
From the MM handbook:
Note that HAS blocks currently do not support the usage of OR or |.
Situations where a patch needs to apply to two seperate requirements
will require two seperate patches.
=> Re-fix restock launchclamps

GameData/KerbalismConfig/System/Parts.cfg
New (BDB) Gemini Equipment Section is missing from the list of Gemini SMs.
=> Add missing Gemini Equipment Section SM config

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Added small holding tanks to processes use things that may not naturally be stored on a craft with them, i.e. LqdMethane to Methane Pyrolosis.
=> Recycler holding tanks

GameData/KerbalismConfig/System/Parts.cfg
Integrating a fuel cell and LOX to GOX converter into the Advanced Capsule resulted in it becoming significantly cheaper and lighter than a Gemini with a service module for the same capabilities. Remove the Fuel Cell and LOX to GOX converter to make it more balanced
=> Nerf Advanced Capsule

GameData/KerbalismConfig/System/Science/SatelliteScience/Experiments/bioSample.cfg
ROKerbalism was relying on its rescaleFactor stacking with the
MODEL.scale applied by RO; but RO no longer sets MODEL.scale, it
sets rescaleFactor.
To get back the old size, must use a rescaleFactor that stacks
with SXT's original MODEL.scale (so 1.25 instead of 0.73)
Downside: the part will now be properly sized when paired with RO master, but will no longer be properly sized when paired with the current RO release. Seems better than the other way around to me, but it's sort of a coin flip.
=> Restore AdvBio to its original size

GameData/KerbalismConfig/ResourceConfigs/Regolith.cfg
RSS has no regolith configs at all. Until it does, this
should make it easier to work with the new regolith processes
=> Better regolith distribution than CRP's

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Because even a mini-drill needs 2.7kW when extracting water full-speed,
and there are limits to how much downstream processes can limit it.
This allows the drill to be hard-limited to 10, 20 or 50% of
max throughput (only in the VAB, sadly)
A few things that could be done differently:
- mass is kept proportional to throughput, with a small penalty the slower it gets; there's arguments for having no penalty, for having a penalty for faster speeds, or to leave it at the full mass regardless of speeds
- ~not done for regolith because I don't have a use case~
- not done for the big drill because it's easy to just use multiple small ones if one big is too much
- specific % values could be anything, obviously
- it could instead be a single config including all values as separate harvesters …
=> Add "throttled" surface harvester configs

GameData/KerbalismConfig/Support/Restock.cfg
Seems restock's models are larger than stock's. Keeping
the same scale factor gave it inset attachment nodes.
=> Fix restock'ed ISRU scale

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg, GameData/KerbalismConfig/Support/RealismOverhaul.cfg, GameData/KerbalismConfig/Support/SXT.cfg
- Match engineType instead of part names, to support both RO's SXT parts
and ROE's parts (and more, maybe)
- Also support NERVA I (the only other engineType with EC output)
- Extract power output from the ModuleResourceConverter instead of hardcoding
(NERVA II was out of sync)
- Apply AFTER RO actually adds the ModuleResourceConverter
(so we can use its value, and so we actually delete it)
=> Fix NTR EC generators

GameData/KerbalismConfig/Support/NearFuture.cfg
Give it the right profile, and inherit capacity from RO's value
N.B. I haven't touched the Emitter module, no clue if its value is RO-plausible. None of the other RTGs have an Emitter at all.
=> Support NFE's lone RTG

GameData/KerbalismConfig/Support/VSR.cfg
Because right now it's a useless prop; it looks inflated but has
no crew capacity and no habitat.
=> Make the InflatableHAB usable

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Got broken when adding the throttled Harvester configs; apparently
multiple SETUPs can't reference the same MODULE instance, only the
last reference "sticks".
=> Fix Regolith Compacter

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
scaled more or less following existing examples;
2x mass increase translates to 4x throughput increase
(actual mass increase factor is higher due to part mass)
ISRU has the SE-RWGS, which is much more efficient than
Sabatier IF you don't want water out of the process.
But if you do want water, chemical plant Sabatier was the
only option and very slow
=> Add Sabatier process to ISRU parts

GameData/KerbalismConfig/System/Resources.cfg
To fix an odd bug: after saving and loading a .craft, the part
cost of every crew part gets reduced by its maximum shielding value
(i.e. the part's habitat surface * unitCost)
=> Make shielding free

GameData/KerbalismConfig/Support/ROCapsules.cfg, GameData/KerbalismConfig/System/Parts.cfg
Kerbalism support for the new ROCapsules Dynasoar. Also revise life support settings.
X-20X was intended to carry 4 passengers and operate for 14 days. However, it also would have been larger than the standard X-20. I have configured the X-20 Dynasoar to hold 2 passengers for 5 days, with capability for longer operations, since it is smaller than the X-20X.
ROC PR: https://github.com/KSP-RO/ROCapsules/pull/110
=> ROCapsules X-20 Moroz Dynasoar support

GameData/KerbalismConfig/System/Science/SatelliteScience/Experiments/Photography.cfg
photo1 is also broken with restock, but since the animation
makes it clear it's not a camera at all, better leave it broken
=> Fix animation name for big cameras

GameData/KerbalismConfig/Support/SSPX.cfg
- Masses, volumes, surface areas, resources are updated to new 1.8 scaling
- Latest SSPX parts, 1.875m (3.38m in RO) and 5m (9m in RO) are now supported
- Tubes, adapters etc. have habitable volumes
- Habitat modules have pre-filled resources for long duration flights
- More advanced habitats provide water purification
- Greenhouses provide resource conversion and comfort
- Centrifuges work and provide comfort
- Extendables carry enough Nitrogen to be used for their extension
- Also, see RO and RP-1 changes
=> Sspx update

GameData/KerbalismConfig/System/Science/HardDriveConfigs.cfg, GameData/KerbalismConfig/System/Science/SatelliteScience/Experiments/Photography.cfg
Add support for the ROC Zenit camera system. This just models the early Zenit models as the improved film camera.
ROC PR: https://github.com/KSP-RO/ROCapsules/pull/114
=> Add support for the ROC Zenit camera system

GameData/KerbalismConfig/System/Science/SatelliteScience/ExperimentValues.cfg
There's been some discussion that maybe the near-zero eccentricity requirement doesn't make sense at all for a Hubble stand-in, but in the meantime, this will make it possible to run the experiment under principia without 20 years of constant manual station keeping
Oddity: the default 0.001 is rendered in-game as 0.0; this 0.005 gets rendered as 0.01. Might be better to make it _actually_ 0.01 to avoid player confusion, but 0.005 was comfortably enough in my experience, doubling it might be too much
=> Make film4 principia-friendly

GameData/KerbalismConfig/Support/NearFuture.cfg
Add full support for NFE fission reactors. Since fuel burnup varies greatly among reactors, create and assign processes specific for each reactor (as suggested by Got). Also make patches compatible with just NFE, and NFE+SystemHeat.
needs https://github.com/KSP-RO/RealismOverhaul/pull/2665
closes https://github.com/KSP-RO/ROKerbalism/pull/82
=> Add full support for NFE reactors

GameData/KerbalismConfig/System/Science/CrewScience/ScienceLabs.cfg
Gate Science converter patches to avoid running on parts with no crew capacity defined at runtime. Resolves BDB wetlabs causing MM errors because they do not define crew capacity at runtime.
=> Gate Science Converter patches better

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Fuel cell values were previously wrong, operating at ~40% efficiency and violating the conservation of mass by producing much less water output than fuel input. Redoing the math based on numbers from the Apollo fuel cell, efficiency has been changed to 80% and stoichiometry redone to obey the conservation of mass.
This should solve issues with Apollo running out of power early, despite having historical J-class propellant loads.
=> Correct fuel cell fuel consumption

GameData/KerbalismConfig/Support/ROCapsules.cfg, GameData/KerbalismConfig/System/Parts.cfg
Adjust life support configs so life support draw is subtracted from capsule avionics draw, instead of just overwriting avionics draw with a new one (why did I even do that)
also configure stuff for the ROC-Gemini overhaul [here](https://github.com/KSP-RO/ROCapsules/pull/149)
=> Use subtract operator instead of just overriding, also Gemini

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Set fuel cells to always dump water, and KO2 scrubbers to always dump oxygen.
Forgetting to set resource dumping is a major trap for new players, and this avoids any possible bugs with kerbalism forgetting to dump (if those haven't been fixed yet).
Although there are potentially niche scenarios in which the player would not want this to happen, breaking those are preferable to the fuel cell and KO2 scrubber not functioning as expected 99% of the time.
=> Autodump water, oxygen

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg, GameData/KerbalismConfig/Support/DECQ_Buran.cfg, GameData/KerbalismConfig/Support/SOCK.cfg, GameData/KerbalismConfig/Support/SSS.cfg, GameData/KerbalismConfig/System/Parts.cfg
Fix bugs with kerbalism fuel cells caused by multiple identical configs. 
Create unique processes for each config to resolve this bug, and also adjust their efficiency a bit to be more realistic. Gemini and Soyuz fuel cells are now less efficient than Apollo fuel cells, while Shuttle fuel cells are slightly more efficient. Finally, correctly tag fuel cells to always dump water, and _only_ water.
Tested, this appears to fix all fuel-cell related bugs that I am aware of, and also ensures a fuel cell will never fail to work due to a full water tank. Vessels in flight with fuel cells (both preset and configurable) will update to their new stats and continue to work.
=> Fix buggy kerbalism fuel cells, and create new types

GameData/KerbalismConfig/System/Habitat.cfg
This is supposed to be balanced as a generic LEM equivalent, but didn't have its habitat volume set leaving it with 10m^3. (It is in the Parts.cfg list of LEMs.)
=> Fix the habitat of the medium lander can

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Add gas generator options to liquefier. These burn a small amount of fuel to rapidly vaporize large amounts of propellant (oxygen, methane, hydrogen). This allows cryogenic scavenging RCS configs to be reliably fed from liquid resources.
=> Add gas generator options to liquifier

GameData/KerbalismConfig/Support/ROCapsules.cfg
add a misplaced zero to subtract the correct amount of mass from the LM ascent stage.
Needs https://github.com/KSP-RO/ROCapsules/pull/158
=> Correct LM ascent stage dry mass

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg, GameData/KerbalismConfig/Support/ROCapsules.cfg, GameData/KerbalismConfig/System/Parts.cfg
Add support for ROCapsules AES LM Phase B parts. Also add a gaseous reactant fuel cell config, based on the AES LM Allis-Chalmers fuel cell.
For https://github.com/KSP-RO/ROCapsules/pull/160/
=> Support for AES LM parts, and gaseous reactant fuel cells

GameData/KerbalismConfig/Localization/en-us.cfg, GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
Add Hydrocarbon fuel cell running on CH4. Still somewhat speculative, using performance data from several different prototypes.
=> Add CH4 fuel cell

GameData/KerbalismConfig/Support/RN_Salyut.cfg
The RN Salyut mod currently has no Kerbalism config, but is configured for RP-1.
This PR adds a config file for the RN Salyut mod, adding basic habitat volume and surface information for the Salyut and Almaz stations. This config file also adds their treadmills.
=> Create RN_Salyut.cfg, add basic habitat and comfort info

GameData/KerbalismConfig/Support/BoringCrewServices.cfg
Changes only made for the Starliner Command Module
=> BoringCrewServices Support

GameData/KerbalismConfig/Support/NearFuture.cfg
Create processes for new reactors, and correctly tag new/updated reactor parts
=> Add kerbalism stuff for new/updated reactors

GameData/KerbalismConfig/System/Habitat.cfg, GameData/KerbalismConfig/System/Sickbay.cfg
For some reason, when a part has its habitat defined in https://github.com/KSP-RO/Kerbalism/blob/7e279c3bccae30eff1ab6612b2b69e78214f4983/GameData/KerbalismConfig/System/Habitat.cfg but NOT in https://github.com/KSP-RO/ROKerbalism/blob/0ae007bf2789abf136ff05367a42e366ecd6dd62/GameData/KerbalismConfig/System/Habitat.cfg, there is a strange bug that massively multiplies that parts volume and surface area by a seemingly random amount.
For example, according to https://github.com/KSP-RO/Kerbalism/blob/7e279c3bccae30eff1ab6612b2b69e78214f4983/GameData/KerbalismConfig/System/Habitat.cfg#L59, landerCabinSmall is supposed to have a volume of 2.1m^3, when it actually has 10.37m^3 ingame.
Another example, according to https://github.com/KSP-RO/Kerbalism/blob/7e279c3bccae30eff1ab6612b2b69e78214f4983/ …
=> Fix the volumes and surface areas of several habitats

GameData/KerbalismConfig/Profiles/ROKerbalism.cfg
resolves https://github.com/KSP-RO/ROKerbalism/issues/169
=> Actually add gaseous fuel cell config to all fuel cells

GameData/KerbalismConfig/Support/NearFuture.cfg
Snap-50 35kw, Snap-2 & Snap-8 NFE reactors show no electrical output in VAB until these pseudo-resources are added
=> Add NFE Snap reactor Pseudo-resources
